# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

aggregation_sumCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_sumCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

aggregation_anyCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_anyCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

aggregation_meanCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_meanCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

aggregation_firstCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_firstCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

aggregation_lastCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_lastCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

aggregation_maxCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_maxCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

aggregation_minCpp <- function(plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph) {
    .Call('_rasterizer_aggregation_minCpp', PACKAGE = 'rasterizer', plot_width, plot_height, x_range, y_range, xlim, ylim, x, y, on, size, glyph)
}

